name: "Yate Server"
description: "Yet Another Telephony Exchange"
version: "0.2.1"
slug: "yate"
startup: services
arch:
  - amd64
host_network: true
init: false
stage: experimental
map:
  - addon_config
image: ghcr.io/mtrnord/yate
services:
  - mysql:want
schema:
  mysql_db: str
  mysql_user: str
  mysql_password: password
